AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Parameters:
  CustomerTableName:
    Type: String
    Default: Customers
  SESEmailAddress:
    Type: String
    Default: arn:aws:ses:us-west-2:710339184759:identity/neuralstyleglacier@gmail.com
Resources:
  SESRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - cognito-idp.amazonaws.com
          Action:
          - sts:AssumeRole
      Policies:
      - PolicyName: CognitoSESPolicy
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Effect: Allow
            Action:
            - ses:SendEmail
            - ses:SendRawEmail
            Resource: arn:aws:ses:us-west-2:710339184759:identity/neuralstyleglacier@gmail.com
  DriverUserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      AdminCreateUserConfig:
        AllowAdminCreateUserOnly: false
      UserPoolName:
        Fn::Sub: ${AWS::StackName}-UserPool
      UsernameAttributes:
      - email
      AutoVerifiedAttributes:
      - email
      EmailConfiguration:
        EmailSendingAccount: COGNITO_DEFAULT
  DriverUserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      ClientName: my-app
      GenerateSecret: false
      UserPoolId:
        Ref: DriverUserPool
      ExplicitAuthFlows:
      - ALLOW_USER_PASSWORD_AUTH
      - ALLOW_REFRESH_TOKEN_AUTH
      - ALLOW_USER_SRP_AUTH
      - ALLOW_CUSTOM_AUTH
      - ALLOW_ADMIN_USER_PASSWORD_AUTH
Outputs:
  DriverUserPool:
    Value:
      Ref: DriverUserPool
    Export:
      Name:
        Fn::Join:
        - ':'
        - - Ref: AWS::StackName
          - DriverUserPool
  DriverUserPoolClient:
    Value:
      Ref: DriverUserPoolClient
    Export:
      Name:
        Fn::Join:
        - ':'
        - - Ref: AWS::StackName
          - DriverUserPoolClient
  UserPoolARN:
    Export:
      Name:
        Fn::Join:
        - ':'
        - - Ref: AWS::StackName
          - DriverUserPoolArn
    Value:
      Fn::GetAtt: DriverUserPool.Arn
